---
- hosts: db_vm
  remote_user: vagrant
  become_method: sudo
  vars:
    db_login: "{{ lookup('env', 'DB_USER') }}"
    db_pass: "{{ lookup('env', 'DB_PASS') }}"
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_ip: "{{ lookup('env', 'DB_HOST') }}"

  tasks:
  - name: instal mysql and MySQL-python
    yum:
      name:
        - mariadb-server
        - MySQL-python
      state: present
    become: yes
  - name: UP MySQL
    systemd:
      name: mariadb
      state: started
      enabled: yes
    become: yes
    
  - name: create DB
    mysql_db:
      name: "{{ db_name }}"
      state: present
      login_user: root

  - name: create user for MySQL
    mysql_user:
      name: '{{ db_login }}'
      password: '{{ db_pass }}'
      login_user: root
      priv: '{{ db_name }}.*:ALL'
      host: 192.168.33.%

  - name: copy config template
    template:
      src: ./config.template
      dest: /etc/my.cnf
    become: yes
    register: new_conf

  - name: restart_MySQL
    systemd:
      name: mariadb
      state: restarted
    become: yes
    when: new_conf is changed

  - name: check user abilities
    mysql_db:
      login_user: "{{ db_login }}"
      login_password: "{{ db_pass }}"
      login_host: "{{ db_ip }}"
      name: "{{ db_name }}"
      state: present 

